### ISSUE TITLE
making this provider official?

### ISSUE THREAD

**Issue by jimsheldon** [mavimo/terraform-provider-drone#47]
Hello!

Thanks for the awesome work on this provider.

The Drone team is interested in making this the official Drone Terraform provider under the `drone` GitHub organization. You would keep maintaining the provider as you have been, just in a different organization where we can get it built and published into the `drone` organization.

If this sounds good, we can discuss next steps.

**Comment by mavimo** [comment]
@jimsheldon sure feel free to write me via email (nickname AT gmail)

**Comment by jimsheldon** [comment]
Hello @mavimo 

I send you an email on the 18th, did you receive it?
